### ISSUE TITLE
Fix search `<Hit>` linking to `id`

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/ov-frontend#77]
Search page links are broken because they are still linking by `id`, rather than `slug`:

```[tasklist]
### Tasks
- [ ] https://github.com/WGBH-MLA/ov-wag/issues/201
- [ ] https://github.com/WGBH-MLA/ov-wag/pull/202
- [x] Update index
- [x] Use slug in `<Hit>`
```
